### ISSUE TITLE
использование по на других телефонах сяоми на snapdragon

### ISSUE THREAD

**Issue by slidekor** [belomaxorka/poco-x3-pro-MI-splash#1]
здравствуйте, хочу узнать можно ли все приложенную инфу использовать с poco x3 nfc?

**Comment by slidekor** [comment]
и программное обеспечение тоже

**Comment by belomaxorka** [comment]
Здравствуйте. Конкретно созданный мною [сплеш](https://github.com/belomaxorka/poco-x3-pro-MI-splash/releases/tag/mi-splash) точно работает на alioth (F3) и vayu (X3 PRO).

Насколько я знаю вышла уже новая версия для создания сплешей у автора, может быть список устройств пополнился. Вот оригинальная [тема](https://4pda.to/forum/index.php?showtopic=1023354&view=findpost&p=114714184).

❤️🕊
